{% set version = "2019.07.04" %}
{% set commit = "52625dd6376a64142a17bc04a6ad59215f5d3118" %}

package:
  name: nltk_data
  version: {{ version }}

source:
  url: https://github.com/nltk/nltk_data/archive/{{ commit }}.tar.gz
  sha256: 25949c8db62684bc9ce7ba9ee26501a75709a096845644e13993ff6aee5d71d7

build:
  number: 1

requirements:
  build:
    - unzip  # [unix]
    - 7za  # [win]
  run:
    - python
    - nltk >=3.4.4

about:
  home: http://nltk.org/
  license: Various
  summary: Data for the Natural Language Toolkit

extra:
  recipe-maintainers:
    - danielfrg
    - quartox
    - benhuff
